# Generated by Django 4.0 on 2024-01-22 11:32

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('name_fa', models.CharField(max_length=150, verbose_name='name_fa')),
                ('name_en', models.CharField(max_length=150, verbose_name='name_en')),
                ('content_en', tinymce.models.HTMLField(verbose_name='content_en')),
                ('content_fa', tinymce.models.HTMLField(verbose_name='content_fa')),
                ('image_en', models.ImageField(upload_to='Category', verbose_name='image_en')),
                ('image_fa', models.ImageField(upload_to='Category', verbose_name='image_fa')),
                ('meta_description_fa', models.TextField(verbose_name='meta_description_fa')),
                ('meta_description_en', models.TextField(verbose_name='meta_description_en')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=150, verbose_name='name_fa')),
                ('name_en', models.CharField(max_length=150, verbose_name='name_en')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('title_fa', models.CharField(max_length=150, verbose_name='title_fa')),
                ('title_en', models.CharField(max_length=150, verbose_name='title_en')),
                ('content_en', tinymce.models.HTMLField(verbose_name='content_en')),
                ('content_fa', tinymce.models.HTMLField(verbose_name='content_fa')),
                ('image_en', models.ImageField(upload_to='Service', verbose_name='image_en')),
                ('image_fa', models.ImageField(upload_to='Service', verbose_name='image_fa')),
                ('date_update', models.DateField(auto_now=True, verbose_name='date_update')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='date_create')),
                ('meta_description_fa', models.TextField(verbose_name='meta_description_fa')),
                ('meta_description_en', models.TextField(verbose_name='meta_description_en')),
                ('views', models.IntegerField(default=0, verbose_name='views')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile', verbose_name='creator')),
                ('tags', models.ManyToManyField(to='service.Tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
