# Generated by Django 5.0.1 on 2024-01-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default='icon', help_text='Fontawesome Class Name', max_length=20, verbose_name='icon'),
            preserve_default=False,
        ),
    ]
