# Generated by Django 5.0.1 on 2024-01-26 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_category_alter_service_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='phone')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_services', to='service.service', verbose_name='service')),
            ],
        ),
    ]
