# Generated by Django 5.0.1 on 2024-01-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_requestedservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='Service', verbose_name='attached_file'),
        ),
    ]
