# Generated by Django 5.0.1 on 2024-01-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='Slide', verbose_name='slider_image')),
                ('link', models.CharField(max_length=50, verbose_name='link')),
            ],
        ),
    ]
