# Generated by Django 5.0.1 on 2024-01-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='link',
            field=models.CharField(blank=True, max_length=50, verbose_name='link'),
        ),
    ]
