# Generated by Django 5.0.1 on 2024-01-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_slide_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='link',
            field=models.URLField(blank=True, max_length=50, null=True, verbose_name='link'),
        ),
    ]
