# Generated by Django 5.0.1 on 2024-01-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_slide_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='slider_image',
        ),
        migrations.AddField(
            model_name='slide',
            name='slider_image_en',
            field=models.ImageField(default='test', upload_to='Slide', verbose_name='slider_image_en'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='slider_image_fa',
            field=models.ImageField(default='test', upload_to='Slide', verbose_name='slider_image_fa'),
            preserve_default=False,
        ),
    ]
