# Generated by Django 5.0.1 on 2024-01-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_slide_slider_image_slide_slider_image_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Customer', verbose_name='image')),
            ],
        ),
        migrations.RemoveField(
            model_name='slide',
            name='slider_image_en',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='slider_image_fa',
        ),
        migrations.AddField(
            model_name='slide',
            name='image_en',
            field=models.ImageField(default='service', upload_to='Slide', verbose_name='image_en'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='image_fa',
            field=models.ImageField(default='service', upload_to='Slide', verbose_name='image_fa'),
            preserve_default=False,
        ),
    ]
