# Generated by Django 5.0.1 on 2024-01-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.CharField(default='qq', help_text='Fontawesome Class Name', max_length=20, verbose_name='icon'),
            preserve_default=False,
        ),
    ]
