# Generated by Django 5.0.1 on 2024-01-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=123, verbose_name='price'),
            preserve_default=False,
        ),
    ]
