# Generated by Django 5.0.1 on 2024-01-25 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150, verbose_name='user')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='date_create')),
                ('comment_description', models.TextField(verbose_name='comment_description')),
                ('published', models.BooleanField(default=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.product')),
            ],
        ),
    ]
