# Generated by Django 5.0.1 on 2024-01-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product',
            new_name='product_table',
        ),
    ]
