# Generated by Django 4.0 on 2024-01-22 11:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('name_fa', models.CharField(max_length=150, verbose_name='name_fa')),
                ('name_en', models.CharField(max_length=150, verbose_name='name_en')),
                ('content_en', tinymce.models.HTMLField(verbose_name='content_en')),
                ('content_fa', tinymce.models.HTMLField(verbose_name='content_fa')),
                ('image_en', models.ImageField(upload_to='Project', verbose_name='image_en')),
                ('image_fa', models.ImageField(upload_to='Project', verbose_name='image_fa')),
                ('meta_description_fa', models.TextField(verbose_name='meta_description_fa')),
                ('meta_description_en', models.TextField(verbose_name='meta_description_en')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
