# Generated by Django 5.0.1 on 2024-01-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(default='tets', help_text='Fontawesome Class Name', max_length=20, verbose_name='icon'),
            preserve_default=False,
        ),
    ]
