# Generated by Django 5.0.1 on 2024-01-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='size',
            field=models.CharField(choices=[('3', 'three'), ('6', 'six')], max_length=50, verbose_name='size'),
        ),
    ]
