# Generated by Django 5.0.1 on 2024-01-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0002_alter_faq_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='shomare',
            field=models.CharField(default='shomare', max_length=50, verbose_name='shomare'),
            preserve_default=False,
        ),
    ]
