# Generated by Django 5.0.1 on 2024-01-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0003_faq_shomare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='shomare',
        ),
    ]
